namespace SIG_Defesa_Civil.API.Enums
{
    public enum TipoUsuario { CIDADAO, ATENDENTE, VISTORIADOR, ADMIN }
    public enum StatusOcorrencia { ABERTA, EM_TRIAGEM, DESPACHADA, EM_VISTORIA, CONCLUIDA, CANCELADA }
    public enum TipoArquivo { FOTO_CIDADAO, COMPROVANTE_RESIDENCIA, FICHA_VISTORIA, FOTO_CAMPO, RELATORIO_FINAL }
    public enum AcaoLgpd { VISUALIZOU, BAIXOU, EDITOU, EXCLUIU, CRIOU }
    public enum ConnectionStrings { PRODCONNECTION, DEVCONNECTION }
    public enum ErrosRequisicoes { UPLOAD_FAILED, ERRO_PROCESSAMENTO, ARQUIVO_MUITO_GRANDE, ARQUIVOS_AUSENTES, VALIDACAO_FALHOU, DADOS_INVALIDOS, JSON_INVALIDO, DADOS_AUSENTES, ERRO_INTERNO }
}
