// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIG_Defesa_Civil.API.Data.Models;

#nullable disable

namespace SIG_Defesa_Civil.API.Migrations
{
    [DbContext(typeof(DefesaCivilContext))]
    [Migration("20260513023349_Alteracao na ficha de vistoria")]
    partial class Alteracaonafichadevistoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("seq_protocolo_ano");

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.AvaliacaoRisco", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AbertaPorUsuarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Emergencia")
                        .HasColumnType("boolean");

                    b.Property<string>("GrauRiscoInicial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OcorrenciaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequisicaoSetorDocumento")
                        .HasColumnType("text");

                    b.Property<string>("TipificacaoInicial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AbertaPorUsuarioId");

                    b.HasIndex("Emergencia");

                    b.HasIndex("GrauRiscoInicial");

                    b.HasIndex("OcorrenciaId")
                        .IsUnique();

                    b.ToTable("avaliacoes_risco");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.EncaminhamentoFinal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int[]>("Encaminhamentos")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("EntregaRelatorio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OcorrenciaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RegistradoPorId")
                        .HasColumnType("integer");

                    b.Property<int?>("RelatorioVistoriaId")
                        .HasColumnType("integer");

                    b.Property<string>("RetornoEncaminhamentos")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OcorrenciaId")
                        .IsUnique();

                    b.HasIndex("RegistradoPorId");

                    b.HasIndex("RelatorioVistoriaId");

                    b.ToTable("encaminhamentos_finais");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Notificado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DataNotificacao")
                        .HasColumnType("date");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OcorrenciaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RegistradoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("RgCpf")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OcorrenciaId");

                    b.HasIndex("RegistradoPorId");

                    b.ToTable("notificados");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Observacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("OcorrenciaId")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OcorrenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Observacoes");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Ocorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AbertaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CriadoPorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DescricaoProblema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ExcluidoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SolicitanteId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AbertaEm");

                    b.HasIndex("CriadoPorId");

                    b.HasIndex("DeletedAt");

                    b.HasIndex("ExcluidoPorId");

                    b.HasIndex("Protocolo")
                        .IsUnique();

                    b.HasIndex("SolicitanteId");

                    b.HasIndex("Status");

                    b.ToTable("ocorrencias");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.TentativaVistoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgendamentoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataHoraTentativa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("NumeroTentativa")
                        .HasColumnType("integer");

                    b.Property<string>("Observacao")
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId", "NumeroTentativa")
                        .IsUnique();

                    b.ToTable("tentativas_vistoria");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Vistoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AgendamentoId")
                        .HasColumnType("integer");

                    b.Property<int[]>("AreasAfetadas")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CaracterizacaoDoLocal")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("DataVistoria")
                        .HasColumnType("date");

                    b.Property<string>("DescricaoDoLocal")
                        .HasColumnType("text");

                    b.Property<string>("Edificacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int[]>("EncaminhamentosDeCampo")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("Estrutura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GrauRiscoEncontrado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<TimeSpan>("HorarioInicio")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HorarioTermino")
                        .HasColumnType("interval");

                    b.Property<string>("Interdicao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int[]>("Motivacao")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroAdultos")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroComodos")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroCriancas")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroDeficientes")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroIdosos")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroMoradias")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroMoradiasNoLote")
                        .HasColumnType("integer");

                    b.Property<int>("NumeroPavimentos")
                        .HasColumnType("integer");

                    b.Property<string>("Observacoes")
                        .HasColumnType("text");

                    b.Property<int>("OcorrenciaId")
                        .HasColumnType("integer");

                    b.Property<int[]>("Orientacoes")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<bool>("PossuiUnidadeFamiliar")
                        .HasColumnType("boolean");

                    b.Property<string>("RegimeOcupacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RegistradoPorId")
                        .HasColumnType("integer");

                    b.Property<string>("Remocao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int[]>("TipificacaoOcorrencia")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<string>("TipoRisco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TotalMoradores")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgendamentoId");

                    b.HasIndex("DataVistoria");

                    b.HasIndex("GrauRiscoEncontrado");

                    b.HasIndex("RegistradoPorId");

                    b.HasIndex("OcorrenciaId", "Numero")
                        .IsUnique();

                    b.ToTable("vistorias");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.AgendamentoVistoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AgendadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AgendadoPorId")
                        .HasColumnType("integer");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<int>("OcorrenciaId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Vistoriador1Id")
                        .HasColumnType("integer");

                    b.Property<int?>("Vistoriador2Id")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgendadoPorId");

                    b.HasIndex("Vistoriador1Id");

                    b.HasIndex("Vistoriador2Id");

                    b.HasIndex("OcorrenciaId", "Numero")
                        .IsUnique();

                    b.ToTable("agendamentos_vistoria");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.Arquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CaminhoRelativo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("caminho_relativo");

                    b.Property<DateTime>("EnviadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("enviado_em");

                    b.Property<int>("EnviadoPorUserId")
                        .HasColumnType("integer")
                        .HasColumnName("enviado_por");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_original");

                    b.Property<int>("OcorrenciaId")
                        .HasColumnType("integer")
                        .HasColumnName("ocorrencia_id");

                    b.Property<long>("TamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamanho_bytes");

                    b.Property<string>("TipoArquivo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tipo_arquivo");

                    b.HasKey("Id");

                    b.HasIndex("CaminhoRelativo")
                        .IsUnique()
                        .HasDatabaseName("idx_arquivos_caminho");

                    b.HasIndex("EnviadoPorUserId");

                    b.HasIndex("OcorrenciaId");

                    b.ToTable("arquivos", (string)null);
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.Localizacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cep")
                        .HasColumnType("text");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Complemento")
                        .HasColumnType("text");

                    b.Property<string>("Coordenada")
                        .HasColumnType("text");

                    b.Property<string>("Endereco")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero")
                        .HasColumnType("text");

                    b.Property<string>("NumeroIptu")
                        .HasColumnType("text");

                    b.Property<int>("OcorrenciaId")
                        .HasColumnType("integer");

                    b.Property<string>("Referencia")
                        .HasColumnType("text");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Bairro");

                    b.HasIndex("Cep");

                    b.HasIndex("OcorrenciaId")
                        .IsUnique();

                    b.ToTable("localizacoes");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.LogAcessoLgpd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ArquivoId")
                        .HasColumnType("integer");

                    b.Property<string>("IpOrigem")
                        .HasColumnType("text");

                    b.Property<int?>("OcorrenciaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArquivoId");

                    b.HasIndex("OcorrenciaId");

                    b.HasIndex("RegistradoEm");

                    b.HasIndex("UsuarioId");

                    b.ToTable("log_acesso_lgpd");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Celular")
                        .HasColumnType("text");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Matricula")
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OrgaoEmissor")
                        .HasColumnType("text");

                    b.Property<string>("Rg")
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.AvaliacaoRisco", b =>
                {
                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "AbertaPorUsuario")
                        .WithMany()
                        .HasForeignKey("AbertaPorUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Ocorrencia", "Ocorrencia")
                        .WithOne("AvaliacaoRisco")
                        .HasForeignKey("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.AvaliacaoRisco", "OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AbertaPorUsuario");

                    b.Navigation("Ocorrencia");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.EncaminhamentoFinal", b =>
                {
                    b.HasOne("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Ocorrencia", "Ocorrencia")
                        .WithOne("EncaminhamentoFinal")
                        .HasForeignKey("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.EncaminhamentoFinal", "OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Arquivo", "RelatorioVistoria")
                        .WithMany()
                        .HasForeignKey("RelatorioVistoriaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ocorrencia");

                    b.Navigation("RegistradoPor");

                    b.Navigation("RelatorioVistoria");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Notificado", b =>
                {
                    b.HasOne("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Ocorrencia", "Ocorrencia")
                        .WithMany("Notificados")
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ocorrencia");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Observacao", b =>
                {
                    b.HasOne("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Ocorrencia", "Ocorrencia")
                        .WithMany("Observacoes")
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ocorrencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Ocorrencia", b =>
                {
                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "CriadoPor")
                        .WithMany()
                        .HasForeignKey("CriadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "ExcluidoPor")
                        .WithMany()
                        .HasForeignKey("ExcluidoPorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "Solicitante")
                        .WithMany()
                        .HasForeignKey("SolicitanteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CriadoPor");

                    b.Navigation("ExcluidoPor");

                    b.Navigation("Solicitante");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.TentativaVistoria", b =>
                {
                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.AgendamentoVistoria", "Agendamento")
                        .WithMany("Tentativas")
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agendamento");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Vistoria", b =>
                {
                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.AgendamentoVistoria", "Agendamento")
                        .WithMany()
                        .HasForeignKey("AgendamentoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Ocorrencia", "Ocorrencia")
                        .WithMany("Vistorias")
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "RegistradoPor")
                        .WithMany()
                        .HasForeignKey("RegistradoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agendamento");

                    b.Navigation("Ocorrencia");

                    b.Navigation("RegistradoPor");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.AgendamentoVistoria", b =>
                {
                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "AgendadoPor")
                        .WithMany()
                        .HasForeignKey("AgendadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Ocorrencia", "Ocorrencia")
                        .WithMany("Agendamentos")
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "Vistoriador1")
                        .WithMany()
                        .HasForeignKey("Vistoriador1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "Vistoriador2")
                        .WithMany()
                        .HasForeignKey("Vistoriador2Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AgendadoPor");

                    b.Navigation("Ocorrencia");

                    b.Navigation("Vistoriador1");

                    b.Navigation("Vistoriador2");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.Arquivo", b =>
                {
                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("EnviadoPorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Ocorrencia", "Ocorrencia")
                        .WithMany("Arquivos")
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ocorrencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.Localizacao", b =>
                {
                    b.HasOne("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Ocorrencia", "Ocorrencia")
                        .WithOne("Localizacao")
                        .HasForeignKey("SIG_Defesa_Civil.API.Data.Models.Tabelas.Localizacao", "OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ocorrencia");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.LogAcessoLgpd", b =>
                {
                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Arquivo", "Arquivo")
                        .WithMany()
                        .HasForeignKey("ArquivoId");

                    b.HasOne("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Ocorrencia", "Ocorrencia")
                        .WithMany()
                        .HasForeignKey("OcorrenciaId");

                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arquivo");

                    b.Navigation("Ocorrencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Entities.Tabelas.Ocorrencia.Ocorrencia", b =>
                {
                    b.Navigation("Agendamentos");

                    b.Navigation("Arquivos");

                    b.Navigation("AvaliacaoRisco");

                    b.Navigation("EncaminhamentoFinal");

                    b.Navigation("Localizacao");

                    b.Navigation("Notificados");

                    b.Navigation("Observacoes");

                    b.Navigation("Vistorias");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.AgendamentoVistoria", b =>
                {
                    b.Navigation("Tentativas");
                });
#pragma warning restore 612, 618
        }
    }
}
