// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SIG_Defesa_Civil.API.Data.Models;

#nullable disable

namespace SIG_Defesa_Civil.API.Migrations
{
    [DbContext(typeof(DefesaCivilContext))]
    [Migration("20260427151715_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence<int>("seq_protocolo_ano");

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.Arquivo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EnviadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EnviadoPor")
                        .HasColumnType("integer");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OcorrenciaId")
                        .HasColumnType("integer");

                    b.Property<string>("SharepointId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SharepointUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoArquivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UsuarioEnvioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OcorrenciaId");

                    b.HasIndex("UsuarioEnvioId");

                    b.ToTable("arquivos");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.LogAcessoLgpd", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ArquivoId")
                        .HasColumnType("integer");

                    b.Property<string>("IpOrigem")
                        .HasColumnType("text");

                    b.Property<int?>("OcorrenciaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ArquivoId");

                    b.HasIndex("OcorrenciaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("log_acesso_lgpd");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.Ocorrencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AbertaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AtendenteId")
                        .HasColumnType("integer");

                    b.Property<int>("CidadaoId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ConcluidaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EnderecoCompleto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("NivelGravidade")
                        .HasColumnType("text");

                    b.Property<string>("Protocolo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoRisco")
                        .HasColumnType("text");

                    b.Property<DateTime?>("TriagemEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VistoriaEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("VistoriadorId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AtendenteId");

                    b.HasIndex("CidadaoId");

                    b.HasIndex("Protocolo")
                        .IsUnique();

                    b.HasIndex("VistoriadorId");

                    b.ToTable("ocorrencias");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rg")
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .HasColumnType("text");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Cpf")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.Arquivo", b =>
                {
                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Ocorrencia", "Ocorrencia")
                        .WithMany("Arquivos")
                        .HasForeignKey("OcorrenciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "UsuarioEnvio")
                        .WithMany()
                        .HasForeignKey("UsuarioEnvioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ocorrencia");

                    b.Navigation("UsuarioEnvio");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.LogAcessoLgpd", b =>
                {
                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Arquivo", "Arquivo")
                        .WithMany()
                        .HasForeignKey("ArquivoId");

                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Ocorrencia", "Ocorrencia")
                        .WithMany()
                        .HasForeignKey("OcorrenciaId");

                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Arquivo");

                    b.Navigation("Ocorrencia");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.Ocorrencia", b =>
                {
                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "Atendente")
                        .WithMany()
                        .HasForeignKey("AtendenteId");

                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "Cidadao")
                        .WithMany()
                        .HasForeignKey("CidadaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SIG_Defesa_Civil.API.Data.Models.Tabelas.Usuario", "Vistoriador")
                        .WithMany()
                        .HasForeignKey("VistoriadorId");

                    b.Navigation("Atendente");

                    b.Navigation("Cidadao");

                    b.Navigation("Vistoriador");
                });

            modelBuilder.Entity("SIG_Defesa_Civil.API.Data.Models.Tabelas.Ocorrencia", b =>
                {
                    b.Navigation("Arquivos");
                });
#pragma warning restore 612, 618
        }
    }
}
